module.exports = {
  GOOD: 'GOOD',
  PROBABLY_GOOD: 'PROBABLY_GOOD',
  AVERAGE: 'AVERAGE',
  PROBABLY_AVERAGE: 'PROBABLY_AVERAGE',
  PROBABLY_LOW: 'PROBABLY_LOW',
  LOW: 'LOW',
  UNKNOWN: 'UNKNOWN'
};
